AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation Template to create an EC2 Instance.
Parameters:
  KeyPairName:
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: Name of an existing EC2 KeyPair.
#    Default: qsworkshop
#  VPCID:
#    Description: 'ID of the VPC (e.g., vpc-0343606e)'
#    Type: 'AWS::EC2::VPC::Id'
#  AccessKey:
#    Type: String
#  SecretAccessKey:
#    Type: String
#  SSHLocation:
#    Description: The IP address range that can be used to SSH to the EC2 instances
#    Type: String
#    MinLength: '9'
#    MaxLength: '18'
#    Default: 0.0.0.0/0
#    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
#    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Metadata:
      'AWS::CloudFormation::Init':
        config:
          packages:
            yum:
              ant: []
#      'AWS::CloudFormation::Authentication':
#        S3AccessCreds:
#          type: S3
#          accessKeyId: !Ref AccessKey
#          secretKey: !Ref SecretAccessKey
    Properties:
#      ImageId: ami-0d8f6eb4f641ef691
      ImageId: ami-04590e7389a6e577c
      InstanceType: t3.medium
#      SecurityGroups:
#        - !Ref InstanceSecurityGroup
      Tags:
        - Key: Name
          Value: pasoe
      KeyName: !Ref KeyPairName
