AWSTemplateFormatVersion: 2010-09-09
Description: >-
   PAS for OpenEdge infrastructure with Auto Scaling (qs-1rus69ti3)
Metadata:
  cfn-lint:
    config:
      ignore_checks:
        - W9002
        - W9003
        - W9006
Parameters:
  DeployBucket:
    Description: S3 bucket containing deployment packages.
    Type: String
    MinLength: 1
  DeployBucketRegion:
    Description: Region in which the deployment packages are stored.
    Type: String
    MinLength: 1
    Default: us-east-1
  PASOEDeployPackage:
    Description: S3 key to deploy databases into PASOE EC2 instances
    Type: String
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t3.large
    AllowedValues:
      - t3.large
      - t3.xlarge
      - t3.2xlarge
      - t3a.large
      - t3a.xlarge
      - t3a.2xlarge
	  - m6i.xlarge
	  - m6i.2xlarge
	  - m6i.4xlarge
	  - m6i.8xlarge
	  - m6i.12xlarge
	  - m6i.16xlarge
	  - m6i.24xlarge
	  - m6i.32xlarge
	  - m6id.xlarge
	  - m6id.2xlarge
	  - m6id.4xlarge
	  - m6id.8xlarge
	  - m6id.12xlarge
	  - m6id.16xlarge
	  - m6id.24xlarge
	  - m6id.32xlarge
	  - m6in.xlarge
	  - m6in.2xlarge
	  - m6in.4xlarge
	  - m6in.8xlarge
	  - m6in.12xlarge
	  - m6in.16xlarge
	  - m6in.24xlarge
	  - m6in.32xlarge
	  - m6idn.xlarge
	  - m6idn.2xlarge
	  - m6idn.4xlarge
	  - m6idn.8xlarge
	  - m6idn.12xlarge
	  - m6idn.16xlarge
	  - m6idn.24xlarge
	  - m6idn.32xlarge
	  - m6a.xlarge
	  - m6a.2xlarge
	  - m6a.4xlarge
	  - m6a.8xlarge
	  - m6a.12xlarge
	  - m6a.16xlarge
	  - m6a.24xlarge
	  - m6a.32xlarge
	  - m6a.48xlarge
	  - c6i.xlarge
	  - c6i.2xlarge
	  - c6i.4xlarge
	  - c6i.8xlarge
	  - c6i.12xlarge
	  - c6i.16xlarge
	  - c6i.24xlarge
	  - c6i.32xlarge
	  - c6id.xlarge
	  - c6id.2xlarge
	  - c6id.4xlarge
	  - c6id.8xlarge
	  - c6id.12xlarge
	  - c6id.16xlarge
	  - c6id.24xlarge
	  - c6id.32xlarge
	  - c6in.xlarge
	  - c6in.2xlarge
	  - c6in.4xlarge
	  - c6in.8xlarge
	  - c6in.12xlarge
	  - c6in.16xlarge
	  - c6in.24xlarge
	  - c6in.32xlarge
	  - c6a.xlarge
	  - c6a.2xlarge
	  - c6a.4xlarge
	  - c6a.8xlarge
	  - c6a.12xlarge
	  - c6a.16xlarge
	  - c6a.24xlarge
	  - c6a.32xlarge
	  - c6a.48xlarge
	  - r6i.xlarge
	  - r6i.2xlarge
	  - r6i.4xlarge
	  - r6i.8xlarge
	  - r6i.12xlarge
	  - r6i.16xlarge
	  - r6i.24xlarge
	  - r6i.32xlarge
	  - r6id.xlarge
	  - r6id.2xlarge
	  - r6id.4xlarge
	  - r6id.8xlarge
	  - r6id.12xlarge
	  - r6id.16xlarge
	  - r6id.24xlarge
	  - r6id.32xlarge
	  - r6in.xlarge
	  - r6in.2xlarge
	  - r6in.4xlarge
	  - r6in.8xlarge
	  - r6in.12xlarge
	  - r6in.16xlarge
	  - r6in.24xlarge
	  - r6in.32xlarge
	  - r6idn.xlarge
	  - r6idn.2xlarge
	  - r6idn.4xlarge
	  - r6idn.8xlarge
	  - r6idn.12xlarge
	  - r6idn.16xlarge
	  - r6idn.24xlarge
	  - r6idn.32xlarge
	  - r6a.xlarge
	  - r6a.2xlarge
	  - r6a.4xlarge
	  - r6a.8xlarge
	  - r6a.12xlarge
	  - r6a.16xlarge
	  - r6a.24xlarge
	  - r6a.32xlarge
	  - r6a.48xlarge
    ConstraintDescription: must be a valid EC2 instance type.
  EmailAddress:
    Description: Email Address for notification
    Type: String
    AllowedPattern: >-
      ([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)
    ConstraintDescription: Must be a valid email id.
  KeyPairName:
    Type: "AWS::EC2::KeyPair::KeyName"
    Description: Name of an existing EC2 KeyPair.
  WebAccessCIDR:
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
    Description: Allowed CIDR block for  webserver access
    Type: String
  PrivateSubnet1ID:
    Description: Private Subnet Id 1
    Type: "AWS::EC2::Subnet::Id"
  PrivateSubnet2ID:
    Description: Private Subnet Id 2
    Type: "AWS::EC2::Subnet::Id"
  PublicSubnet1ID:
    Description: Public Subnet Id 1
    Type: "AWS::EC2::Subnet::Id"
  PublicSubnet2ID:
    Description: Public Subnet Id 2
    Type: "AWS::EC2::Subnet::Id"
  VPCID:
    Description: "ID of the VPC (e.g., vpc-0343606e)"
    Type: "AWS::EC2::VPC::Id"
  DBHostName:
    Description: IP Address of SourceReplica Instance
    Type: String
  DBHostName1:
    Description: IP Address of SourceReplica Instance
    Type: String
  DBHostName2:
    Description: IP Address of SourceReplica Instance
    Type: String
  MinScalingInstances:
    Description: Minimum number of EC2 instances in ASG
    Type: String
  MaxScalingInstances:
    Description: Maximum number of EC2 instances in ASG
    Type: String
Mappings:
  AWSAMIRegionMap:
    AMI:
      PASOEAMZNLINUX2: Amazon Linux 2 AMI with PAS for OpenEdge
    af-south-1:
      PASOEAMZNLINUX2: ami-0c281b154dd811948
    ap-east-1:
      PASOEAMZNLINUX2: ami-0b61a0507f9c4b3dc
    ap-northeast-1:
      PASOEAMZNLINUX2: ami-09532d784a4b748f6
    ap-northeast-2:
      PASOEAMZNLINUX2: ami-04f9062f218e2e470
    ap-south-1:
      PASOEAMZNLINUX2: ami-07955cfec4b6e87ad
    ap-southeast-1:
      PASOEAMZNLINUX2: ami-0cd5f8a8496a1901c
    ap-southeast-2:
      PASOEAMZNLINUX2: ami-0f226445cb78c05d8
    ca-central-1:
      PASOEAMZNLINUX2: ami-0289a0b4ad342adc5
    eu-central-1:
      PASOEAMZNLINUX2: ami-08e0f0207d1ab58b0
    eu-north-1:
      PASOEAMZNLINUX2: ami-02c0d0e2eaf72abf4
    eu-south-1:
      PASOEAMZNLINUX2: ami-099fcf343ced32d87
    eu-west-1:
      PASOEAMZNLINUX2: ami-0f40ef92d4e0987c6
    eu-west-2:
      PASOEAMZNLINUX2: ami-0e079c6a6f04b774c
    eu-west-3:
      PASOEAMZNLINUX2: ami-08f880de72910f409
    sa-east-1:
      PASOEAMZNLINUX2: ami-05a9dbddb4865f867
    us-east-1:
      PASOEAMZNLINUX2: ami-01509876f9479d692
    us-east-2:
      PASOEAMZNLINUX2: ami-0e64ee530d5e7296d
    us-west-1:
      PASOEAMZNLINUX2: ami-08511b1e7eff4797d
    us-west-2:
      PASOEAMZNLINUX2: ami-0eb4dcdcc76f797f3
Resources:
  NotificationTopic:
    Type: "AWS::SNS::Topic"
    Properties:
      Subscription:
        - Endpoint: !Ref EmailAddress
          Protocol: email
  S3AccessRole:
    Type: "AWS::IAM::Role"
    Properties:
      Path: "/"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - 'ec2.amazonaws.com'
          Action: sts:AssumeRole
  S3AccessRolePolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: S3AccessRolePolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Action:
          - s3:Get*
          - s3:List*
          - s3:AbortMultipartUpload
          Resource:
            - !Sub 'arn:${AWS::Partition}:s3:::${DeployBucket}/${PASOEDeployPackage}*'
            - !Sub 'arn:${AWS::Partition}:s3:::${DeployBucket}'
            - !Sub 'arn:${AWS::Partition}:s3:::${DeployBucket}/*'
      Roles:
        - Ref: S3AccessRole
  S3AccessProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: /
      Roles:
        - !Ref S3AccessRole
  PASOEGroup:
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    Properties:
      VPCZoneIdentifier:
        - !Ref PrivateSubnet1ID
        - !Ref PrivateSubnet2ID
      LaunchConfigurationName: !Ref PASOELaunchConfig
      MinSize: !Ref MinScalingInstances
      MaxSize: !Ref MaxScalingInstances
      TargetGroupARNs:
        - !Ref PASOETargetGroup
      NotificationConfigurations:
      - TopicARN: !Ref NotificationTopic
        NotificationTypes:
          - autoscaling:EC2_INSTANCE_LAUNCH
          - autoscaling:EC2_INSTANCE_LAUNCH_ERROR
          - autoscaling:EC2_INSTANCE_TERMINATE
          - autoscaling:EC2_INSTANCE_TERMINATE_ERROR
      Tags:
        - Key: Name
          Value: pasoe
          PropagateAtLaunch: true
    CreationPolicy:
      ResourceSignal:
        Timeout: PT15M
        Count: '1'
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MinInstancesInService: 1
        MaxBatchSize: 1
        PauseTime: PT15M
        WaitOnResourceSignals: true
  PASOELaunchConfig:
    Type: 'AWS::AutoScaling::LaunchConfiguration'
    Metadata:
#      "AWS::CloudFormation::Init":
#        config:
#          awscli:
#            commands:
#              00_set_default_s3_signature_version:
#                command: aws configure set default.s3.signature_version s3v4
#              01_set_default_region:
#                command: !Sub "aws configure set default.region '${DeployBucketRegion}'"
#          files:
#            "/install/app.tar.gz":
#              source: !Sub 'https://${DeployBucket}.s3.${DeployBucketRegion}.${AWS::URLSuffix}/${PASOEDeployPackage}'
#              mode: '000755'
#              owner: ec2-user
#              group: ec2-user
#              authentication: S3AccessCreds
      'AWS::CloudFormation::Authentication':
        S3AccessCreds:
          type: S3
          roleName: !Ref S3AccessRole
    Properties:
      IamInstanceProfile: !Ref S3AccessProfile
      KeyName: !Ref KeyPairName
      ImageId: !FindInMap
        - AWSAMIRegionMap
        - !Ref 'AWS::Region'
        - PASOEAMZNLINUX2
      InstanceType: !Ref InstanceType
      SecurityGroups:
        - !Ref PASOESecurityGroup
      UserData: !Base64
        'Fn::Sub':
          - >
            #!/bin/bash -x

            # Install PASOE app

            mkdir -p /install

            aws configure set default.s3.signature_version s3v4

            aws configure set default.region ${DeployRegion}

            aws s3 cp ${DeployPackage} /install/app.tar.gz

            export OE_ENV=pasoe

            export DBHostName=${DBHostName}

            export DBHostName1=${DBHostName1}

            export DBHostName2=${DBHostName2}

            /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource PASOELaunchConfig --region ${AWS::Region}

            tar xCf /install /install/app.tar.gz

            /install/app/deploy.sh

            /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource PASOEGroup --region ${AWS::Region}

            #            [ $(qs_status) == 0 ] && cfn_success || cfn_fail

          - DeployRegion: !Ref DeployBucketRegion
            DeployPackage: !Sub 's3://${DeployBucket}/${PASOEDeployPackage}'
  PASOEScaleUpPolicy:
    Type: 'AWS::AutoScaling::ScalingPolicy'
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName: !Ref PASOEGroup
      Cooldown: '60'
      ScalingAdjustment: 1
  PASOEScaleDownPolicy:
    Type: 'AWS::AutoScaling::ScalingPolicy'
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName: !Ref PASOEGroup
      Cooldown: '60'
      ScalingAdjustment: -1
  WebServerCPUAlarmHigh:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmDescription: Scale-up if CPU > 90% for 10 minutes
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 90
      AlarmActions:
        - !Ref PASOEScaleUpPolicy
      Dimensions:
        - Name: AutoScalingGroupName
          Value: !Ref PASOEGroup
      ComparisonOperator: GreaterThanThreshold
  WebServerCPUAlarmLow:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmDescription: Scale-down if CPU < 70% for 10 minutes
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 70
      AlarmActions:
        - !Ref PASOEScaleDownPolicy
      Dimensions:
        - Name: AutoScalingGroupName
          Value: !Ref PASOEGroup
      ComparisonOperator: LessThanThreshold
  ApplicationLoadBalancer:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      Subnets:
        - !Ref PublicSubnet1ID
        - !Ref PublicSubnet2ID
      SecurityGroups:
        - !Ref ELBPASOESecurityGroup
      Tags:
        - Key: name
          Value:  WebServer ASG Instance
  PASOEListener:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref PASOETargetGroup
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP
  PASOETargetGroup:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 3
      Port: 8810
      Protocol: HTTP
      UnhealthyThresholdCount: 5
      VpcId: !Ref VPCID
  PASOESecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: F1000
            reason: "Standard Amazon practice"
    Properties:
      GroupDescription: Enable access to the PASOE EC2 Instance
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: '0.0.0.0/0'
        - IpProtocol: tcp
          FromPort: 8810
          ToPort: 8810
          CidrIp: '0.0.0.0/0'
        - IpProtocol: tcp
          FromPort: 8811
          ToPort: 8811
          CidrIp: '0.0.0.0/0'
      VpcId: !Ref VPCID
  ELBPASOESecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: F1000
            reason: "Standard Amazon practice"
    Properties:
      GroupDescription: Enable HTTP to the load balancer
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: !Ref WebAccessCIDR
      VpcId: !Ref VPCID
Outputs:
  URL:
    Description: The URL of PASOE
    Value: !Join
      - ''
      - - 'http://'
        - !GetAtt
          - ApplicationLoadBalancer
          - DNSName

