AWSTemplateFormatVersion: 2010-09-09
Description: >-
  OpenEdge Database infrastructure with Replication Set (qs-1rus69tf0)
Metadata:
  cfn-lint:
    config:
      ignore_checks:
        - W9002
        - W9003
        - W9006
Parameters:
  DeployBucket:
    Description: S3 bucket containing deployment packages.
    Type: String
    MinLength: 1
  DeployBucketRegion:
    Description: Region in which the deployment packages are stored.
    Type: String
    MinLength: 1
    Default: us-east-1
  DBDeployPackage:
    Description: URL to package to deploy databases into database EC2 instances
    Type: String
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t3a.medium
    AllowedValues:
      - t3a.small
      - t3a.medium
      - t3a.large
      - t3a.xlarge
      - t3a.2xlarge
    ConstraintDescription: must be a valid EC2 instance type.
  EmailAddress:
    Description: Email Address for notification
    Type: String
    AllowedPattern: >-
      ([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)
    ConstraintDescription: Must be a valid email id.
  KeyPairName:
    Type: "AWS::EC2::KeyPair::KeyName"
    Description: Name of an existing EC2 KeyPair.
  PrivateSubnet1ID:
    Description: Private Subnet Id 1
    Type: "AWS::EC2::Subnet::Id"
  PrivateSubnet2ID:
    Description: Private Subnet Id 2
    Type: "AWS::EC2::Subnet::Id"
  VPCID:
    Description: "ID of the VPC (e.g., vpc-0343606e)"
    Type: "AWS::EC2::VPC::Id"
  PortNumber:
    Description: Port number to use to connect to the database broker process
    Type: Number
  MinPort:
    Description: Use Minimum Dynamic Server (-minport) number to specify the lowest port number in a specified range of port numbers accessible to a client.
    Type: Number
    Default: 1025
  MaxPort:
    Description: Use Maximum Dynamic Server (-minport) number to specify the highest port number in a specified range of port numbers accessible to a client.
    Type: Number
    Default: 2000
Mappings:
  AWSAMIRegionMap:
    AMI:
      OEDBAMZNLINUX2: Amazon Linux 2 AMI with OpenEdge Database
    af-south-1:
      PASOEAMZNLINUX2: ami-0483b4c1afb4eda46
    ap-east-1:
      PASOEAMZNLINUX2: ami-0f34f73c9c1c4c5a1
    ap-northeast-1:
      PASOEAMZNLINUX2: ami-029df9bb050ef8112
    ap-northeast-2:
      PASOEAMZNLINUX2: ami-0e229f9260ad0b013
    ap-south-1:
      PASOEAMZNLINUX2: ami-02a0dbded0d8b8096
    ap-southeast-1:
      PASOEAMZNLINUX2: ami-0a0385bc25f45793e
    ap-southeast-2:
      PASOEAMZNLINUX2: ami-0871f7e7f3afeedb3
    ca-central-1:
      PASOEAMZNLINUX2: ami-0aeaeac94c2608b8f
    eu-central-1:
      PASOEAMZNLINUX2: ami-0a2e6a23a0a4781b9
    eu-north-1:
      PASOEAMZNLINUX2: ami-05fbeddf4f4483977
    eu-south-1:
      PASOEAMZNLINUX2: ami-0347b276719afd4e4
    eu-west-1:
      PASOEAMZNLINUX2: ami-0d11972d0008af076
    eu-west-2:
      PASOEAMZNLINUX2: ami-0cb95ff0a8a76a9a8
    eu-west-3:
      PASOEAMZNLINUX2: ami-00a3f3b6e1e30a117
    sa-east-1:
      PASOEAMZNLINUX2: ami-09a5810b9df3765b3
    us-east-1:
      PASOEAMZNLINUX2: ami-0a0664d4ac87ed6b6
    us-east-2:
      PASOEAMZNLINUX2: ami-092fe5237e3926fde
    us-west-1:
      PASOEAMZNLINUX2: ami-04ddd8681266f6db9
    us-west-2:
      PASOEAMZNLINUX2: ami-08c078385c21f45ef
Resources:
  NotificationTopic:
    Type: "AWS::SNS::Topic"
    Properties:
      Subscription:
        - Endpoint: !Ref EmailAddress
          Protocol: email
  S3AccessRole:
    Type: "AWS::IAM::Role"
    Properties:
      Path: "/"     
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - 'ec2.amazonaws.com'
          Action: sts:AssumeRole
  S3AccessRolePolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: S3AccessRolePolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:       
        - Effect: Allow
          Action:
          - s3:Get*
          - s3:List*
          - s3:AbortMultipartUpload
          Resource:
            - !Sub 'arn:${AWS::Partition}:s3:::${DeployBucket}/${DBDeployPackage}*'
            - !Sub 'arn:${AWS::Partition}:s3:::${DeployBucket}'
            - !Sub 'arn:${AWS::Partition}:s3:::${DeployBucket}/*'
      Roles:
        - Ref: S3AccessRole
  S3AccessProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: /
      Roles:
        - !Ref S3AccessRole
  TargetReplicaOne:
    Type: "AWS::EC2::Instance"
    Metadata:
      'AWS::CloudFormation::Authentication':
        S3AccessCreds:
          type: S3
          roleName: !Ref S3AccessRole
    Properties:
      IamInstanceProfile: !Ref S3AccessProfile
      ImageId: !FindInMap
        - AWSAMIRegionMap
        - !Ref 'AWS::Region'
        - OEDBAMZNLINUX2
      InstanceType: !Ref InstanceType
      SubnetId: !Ref PrivateSubnet2ID
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      Tags:
        - Key: Name
          Value: db1
      KeyName: !Ref KeyPairName
      UserData: !Base64 
        'Fn::Sub':
          - >
            #!/bin/bash -x

            # Setup Databases

            mkdir -p /install

            aws configure set default.s3.signature_version s3v4

            aws configure set default.region ${DeployRegion}

            aws s3 cp ${DeployPackage} /install/app.tar.gz

            OE_ENV=db1

            export OE_ENV

            /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource SourceReplica --region ${AWS::Region}

            tar xCf /install /install/app.tar.gz

            /install/app/deploy.sh

          - DeployRegion: !Ref DeployBucketRegion
            DeployPackage: !Sub 's3://${DeployBucket}/${DBDeployPackage}'   
  TargetReplicaTwo:
    Type: "AWS::EC2::Instance"
    Metadata:
      'AWS::CloudFormation::Authentication':
        S3AccessCreds:
          type: S3
          roleName: !Ref S3AccessRole
    Properties:
      IamInstanceProfile: !Ref S3AccessProfile
      ImageId: !FindInMap
        - AWSAMIRegionMap
        - !Ref 'AWS::Region'
        - OEDBAMZNLINUX2
      InstanceType: !Ref InstanceType
      SubnetId: !Ref PrivateSubnet1ID
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      Tags:
        - Key: Name
          Value: db2
      KeyName: !Ref KeyPairName
      UserData: !Base64 
        'Fn::Sub':
          - >
            #!/bin/bash -x

            # Setup Databases

            mkdir -p /install

            aws configure set default.s3.signature_version s3v4

            aws configure set default.region ${DeployRegion}

            aws s3 cp ${DeployPackage} /install/app.tar.gz

            OE_ENV=db2

            export OE_ENV

            /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource SourceReplica --region ${AWS::Region}

            tar xCf /install /install/app.tar.gz

            /install/app/deploy.sh

          - DeployRegion: !Ref DeployBucketRegion
            DeployPackage: !Sub 's3://${DeployBucket}/${DBDeployPackage}'
  SourceReplica:
    Type: "AWS::EC2::Instance"
    Metadata:
      'AWS::CloudFormation::Authentication':
        S3AccessCreds:
          type: S3
          roleName: !Ref S3AccessRole
    Properties:
      IamInstanceProfile: !Ref S3AccessProfile
      ImageId: !FindInMap
        - AWSAMIRegionMap
        - !Ref 'AWS::Region'
        - OEDBAMZNLINUX2
      InstanceType: !Ref InstanceType
      SubnetId: !Ref PrivateSubnet1ID
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      Tags:
        - Key: Name
          Value: db0
      KeyName: !Ref KeyPairName
      UserData: !Base64 
        'Fn::Sub':
          - >
            #!/bin/bash -x

            # Setup Databases

            aws configure set default.s3.signature_version s3v4

            aws configure set default.region ${DeployRegion}

            mkdir -p /install

            aws s3 cp ${DeployPackage} /install/app.tar.gz

            export OE_ENV=db0
            
            export DBHostName=`curl http://169.254.169.254/latest/meta-data/local-ipv4`

            export DBHostName1=${DBHostName1}
            
            export DBHostName2=${DBHostName2}            

            /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource SourceReplica --region ${AWS::Region}

            tar xCf /install /install/app.tar.gz

            /install/app/deploy.sh

          - DeployRegion: !Ref DeployBucketRegion
            DeployPackage: !Sub 's3://${DeployBucket}/${DBDeployPackage}'
            DBHostName1:
              Fn::GetAtt:
                - TargetReplicaOne
                - PrivateIp
            DBHostName2:
              Fn::GetAtt:
                - TargetReplicaTwo
                - PrivateIp            
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: F1000
            reason: "Standard Amazon practice"
    Properties:
      GroupDescription: Enable access to the Database Instance (SSH, DB)
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: '0.0.0.0/0'
        - IpProtocol: tcp
          FromPort: !Ref MinPort
          ToPort: !Ref MaxPort
          CidrIp: '0.0.0.0/0'
        - IpProtocol: tcp
          FromPort: !Ref PortNumber
          ToPort: !Ref PortNumber
          CidrIp: '0.0.0.0/0'
      VpcId: !Ref VPCID
Outputs:
  DBHostName:
    Description: Private IP Address of db0 instance
    Value:
      Fn::GetAtt:
      - SourceReplica
      - PrivateIp
  DBHostName1:
    Description: Private IP Address of db0 instance
    Value:
      Fn::GetAtt:
      - TargetReplicaOne
      - PrivateIp
  DBHostName2:
    Description: Private IP Address of db0 instance
    Value:
      Fn::GetAtt:
      - TargetReplicaTwo
      - PrivateIp
