AWSTemplateFormatVersion: 2010-09-09
Description: >-
   PAS for OpenEdge infrastructure with Auto Scaling
Parameters:
  PASOEDeployPackage:
    Description: URL to package to deploy databases into PASOE EC2 instances
    Type: String
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t3a.small
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
      - t3a.small
      - m4.large
      - m4.xlarge
      - m4.2xlarge
      - m4.4xlarge
      - m4.10xlarge
      - c4.large
      - c4.xlarge
      - c4.2xlarge
      - c4.4xlarge
      - c4.8xlarge
      - r4.large
      - r4.xlarge
      - r4.2xlarge
      - r4.4xlarge
      - r4.8xlarge
    ConstraintDescription: must be a valid EC2 instance type.
  EmailAddress:
    Description: Email Address for notification
    Type: String
    AllowedPattern: >-
      ([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)
    ConstraintDescription: Must be a valid email id.
  KeyPairName:
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: Name of an existing EC2 KeyPair.
  WebserverCIDR:
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
    Description: Allowed CIDR block for  webserver access
    Type: String
  RemoteAccessCIDR:
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
    Description: Allowed CIDR block for external SSH access
    Type: String
  QSS3BucketName:
    AllowedPattern: '^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$'
    ConstraintDescription: >-
      Quick Start bucket name can include numbers, lowercase letters, uppercase
      letters, and hyphens (-). It cannot start or end with a hyphen (-).
    Default: aws-quickstart
    Description: >-
      S3 bucket name for the Quick Start assets. Quick Start bucket name can
      include numbers, lowercase letters, uppercase letters, and hyphens (-). It
      cannot start or end with a hyphen (-).
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: '^[0-9a-zA-Z-/]*$'
    ConstraintDescription: >-
      Quick Start key prefix can include numbers, lowercase letters, uppercase
      letters, hyphens (-), and forward slash (/).
    Default: implementing/
    Description: >-
      S3 key prefix for the Quick Start assets. Quick Start key prefix can
      include numbers, lowercase letters, uppercase letters, hyphens (-), and
      forward slash (/).
    Type: String
  PrivateSubnet1ID:
    Description: Private Subnet Id 1
    Type: 'AWS::EC2::Subnet::Id'
  PrivateSubnet2ID:
    Description: Private Subnet Id 2
    Type: 'AWS::EC2::Subnet::Id'
  PublicSubnet1ID:
    Description: Public Subnet Id 1
    Type: 'AWS::EC2::Subnet::Id'
  PublicSubnet2ID:
    Description: Public Subnet Id 2
    Type: 'AWS::EC2::Subnet::Id'
  VPCID:
    Description: 'ID of the VPC (e.g., vpc-0343606e)'
    Type: 'AWS::EC2::VPC::Id'
  VPCCIDR:
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: Must be a valid IP range in x.x.x.x/x notation
    Description: The CIDR IP range of VPC
    Type: String
  DBHostName:
    Description: IP Address of SourceReplica Instance
    Type: String
  DBHostName1:
    Description: IP Address of SourceReplica Instance
    Type: String
  DBHostName2:
    Description: IP Address of SourceReplica Instance
    Type: String
Mappings:
  AWSAMIRegionMap:
    AMI:
      PASOEAMZNLINUX2: Amazon Linux 2 AMI with PAS for OpenEdge
    af-south-1:
      PASOEAMZNLINUX2: ami-0ea122635924978c0
    ap-east-1:
      PASOEAMZNLINUX2: ami-06ac67cc7637b9e50
    ap-northeast-1:
      PASOEAMZNLINUX2: ami-09f769a3e6c95a641
    ap-northeast-2:
      PASOEAMZNLINUX2: ami-07112fc814adbb484
    ap-northeast-3:
      PASOEAMZNLINUX2: ami-0c8ff26e49b608b64
    ap-south-1:
      PASOEAMZNLINUX2: ami-010e0cdc17aac0c62
    ap-southeast-1:
      PASOEAMZNLINUX2: ami-0461ac5bfe6c2bb3b
    ap-southeast-2:
      PASOEAMZNLINUX2: ami-07d619bb2d35e1941
    ca-central-1:
      PASOEAMZNLINUX2: ami-0e48a91a531305c17
    eu-central-1:
      PASOEAMZNLINUX2: ami-00f2f26f5212e4790
    eu-north-1:
      PASOEAMZNLINUX2: ami-0b146ea1e44c356f9
    eu-south-1:
      PASOEAMZNLINUX2: ami-0104627b5f3b6042e
    eu-west-1:
      PASOEAMZNLINUX2: ami-01fb0eb0b78795a05
    eu-west-2:
      PASOEAMZNLINUX2: ami-0992605119c32062c
    eu-west-3:
      PASOEAMZNLINUX2: ami-0d2f60f662582e252
    me-south-1:
      PASOEAMZNLINUX2: ami-0a058cc63da7db45b
    sa-east-1:
      PASOEAMZNLINUX2: ami-0c4cda3f8934cf9cc
    us-east-1:
      PASOEAMZNLINUX2: ami-0889b81877c178bac
    us-east-2:
      PASOEAMZNLINUX2: ami-038b2f23053b3a462
    us-west-1:
      PASOEAMZNLINUX2: ami-02898a71d0d57337f
    us-west-2:
      PASOEAMZNLINUX2: ami-097e290f0ee541123
Conditions:
  GovCloudCondition: !Equals 
    - !Ref 'AWS::Region'
    - us-gov-west-1
Resources:
  NotificationTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      Subscription:
        - Endpoint: !Ref EmailAddress
          Protocol: email
  PASOEGroup:
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    Properties:
      VPCZoneIdentifier:
        - !Ref PrivateSubnet1ID
        - !Ref PrivateSubnet2ID
      LaunchConfigurationName: !Ref PASOELaunchConfig
      MinSize: '2'
      MaxSize: '8'
      TargetGroupARNs:
        - !Ref PASOETargetGroup
      NotificationConfigurations:
      - TopicARN: !Ref NotificationTopic
        NotificationTypes:
          - autoscaling:EC2_INSTANCE_LAUNCH
          - autoscaling:EC2_INSTANCE_LAUNCH_ERROR
          - autoscaling:EC2_INSTANCE_TERMINATE
          - autoscaling:EC2_INSTANCE_TERMINATE_ERROR
      Tags:
        - Key: Name
          Value: pasoe
          PropagateAtLaunch: true
    CreationPolicy:
      ResourceSignal:
        Timeout: PT15M
        Count: '1'
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MinInstancesInService: 1
        MaxBatchSize: 1
        PauseTime: PT15M
        WaitOnResourceSignals: true
  PASOELaunchConfig:
    Type: 'AWS::AutoScaling::LaunchConfiguration'
    Properties:
      KeyName: !Ref KeyPairName
      ImageId: !FindInMap 
        - AWSAMIRegionMap
        - !Ref 'AWS::Region'
        - PASOEAMZNLINUX2
      InstanceType: !Ref InstanceType
      SecurityGroups:
        - !Ref PASOESecurityGroup
      UserData: !Base64
        'Fn::Sub':
          - >
            #!/bin/bash -x

            # Install PASOE app

            mkdir -p /install

            wget -O /install/app.tar.gz ${PASOEDeployPackage}

            OE_ENV=pasoe

            DBHostName=${DBHostName}

            export OE_ENV DBHostName

            DBHostName1=${DBHostName1}

            export OE_ENV DBHostName1

            DBHostName2=${DBHostName2}

            export OE_ENV DBHostName2

            tar xCf /install /install/app.tar.gz

            echo ${DBHostName} >> /tmp/output.txt


            echo ${DBHostName} >> /tmp/output.txt

            /install/app/deploy.sh

            # Signal cfn-init (final check)

            #/opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource PASOELaunchConfig --region ${AWS::Region}

            /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource PASOEGroup --region ${AWS::Region}

            #            [ $(qs_status) == 0 ] && cfn_success || cfn_fail
          - S3Region: !If
              - GovCloudCondition
              - s3-us-gov-west-1
              - s3
  PASOEScaleUpPolicy:
    Type: 'AWS::AutoScaling::ScalingPolicy'
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName: !Ref PASOEGroup
      Cooldown: '60'
      ScalingAdjustment: 1
  PASOEScaleDownPolicy:
    Type: 'AWS::AutoScaling::ScalingPolicy'
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName: !Ref PASOEGroup
      Cooldown: '60'
      ScalingAdjustment: -1
  WebServerCPUAlarmHigh:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmDescription: Scale-up if CPU > 90% for 10 minutes
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 90
      AlarmActions:
        - !Ref PASOEScaleUpPolicy
      Dimensions:
        - Name: AutoScalingGroupName
          Value: !Ref PASOEGroup
      ComparisonOperator: GreaterThanThreshold
  WebServerCPUAlarmLow:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmDescription: Scale-down if CPU < 70% for 10 minutes
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 70
      AlarmActions:
        - !Ref PASOEScaleDownPolicy
      Dimensions:
        - Name: AutoScalingGroupName
          Value: !Ref PASOEGroup
      ComparisonOperator: LessThanThreshold
  ApplicationLoadBalancer:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      Subnets:
        - !Ref PublicSubnet1ID
        - !Ref PublicSubnet2ID
      SecurityGroups:
        - !Ref PASOESecurityGroup
      Tags:
        - Key: name
          Value:  WebServer ASG Instance
  PASOEListener:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref PASOETargetGroup
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP
  PASOETargetGroup:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 3
      Port: 8810
      Protocol: HTTP
      UnhealthyThresholdCount: 5
      VpcId: !Ref VPCID
  PASOESecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable HTTP to PASOE from the load balancer and SSH Access from RemoteAccessCIDR
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref RemoteAccessCIDR
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: !Ref WebserverCIDR
        - IpProtocol: tcp
          FromPort: 8810
          ToPort: 8810
          CidrIp: !Ref WebserverCIDR
        - IpProtocol: tcp
          FromPort: 8811
          ToPort: 8811
          CidrIp: !Ref WebserverCIDR
      VpcId: !Ref VPCID
Outputs:
  URL:
    Description: The URL of PASOE
    Value: !Join 
      - ''
      - - 'http://'
        - !GetAtt 
          - ApplicationLoadBalancer
          - DNSName

